# Generated by Django 3.0.5 on 2024-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='date_approved',
            field=models.DateField(null=True),
        ),
    ]
