# Generated by Django 3.0.5 on 2024-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=3)),
                ('donation_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=3),
        ),
    ]
