# Generated by Django 3.0.5 on 2024-07-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_auto_20240723_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonation',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
