# Generated by Django 3.0.5 on 2024-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='date_approved',
            field=models.DateField(null=True),
        ),
    ]
